//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leilao
    {
        public int artigoId { get; set; }
        public decimal licitacaoMin { get; set; }
        public decimal valorMin { get; set; }
    
        public virtual Artigo Artigo { get; set; }
    }
}
