//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ISELEntities2 : DbContext
    {
        public ISELEntities2()
            : base("name=ISELEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigo> Artigo { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<HistoricoUtilizador> HistoricoUtilizador { get; set; }
        public virtual DbSet<Leilao> Leilao { get; set; }
        public virtual DbSet<Licitacao> Licitacao { get; set; }
        public virtual DbSet<Porte> Porte { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
        public virtual DbSet<Venda> Venda { get; set; }
        public virtual DbSet<VendaDirecta> VendaDirecta { get; set; }
        public virtual DbSet<leilaoNaoConcluido> leilaoNaoConcluido { get; set; }
    
        [DbFunction("ISELEntities2", "nLicitacao")]
        public virtual IQueryable<nLicitacao_Result> nLicitacao(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<nLicitacao_Result>("[ISELEntities2].[nLicitacao](@n)", nParameter);
        }
    
        [DbFunction("ISELEntities2", "valorLicit")]
        public virtual IQueryable<valorLicit_Result> valorLicit(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<valorLicit_Result>("[ISELEntities2].[valorLicit](@id)", idParameter);
        }
    
        public virtual int apagarArtigo(Nullable<int> artigoId)
        {
            var artigoIdParameter = artigoId.HasValue ?
                new ObjectParameter("artigoId", artigoId) :
                new ObjectParameter("artigoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("apagarArtigo", artigoIdParameter);
        }
    
        public virtual int apagarLocal(string local)
        {
            var localParameter = local != null ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("apagarLocal", localParameter);
        }
    
        public virtual int apagarUtilizador(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("apagarUtilizador", emailParameter);
        }
    
        public virtual int atualizarArtigo(Nullable<int> update1, Nullable<int> artigoId)
        {
            var update1Parameter = update1.HasValue ?
                new ObjectParameter("update1", update1) :
                new ObjectParameter("update1", typeof(int));
    
            var artigoIdParameter = artigoId.HasValue ?
                new ObjectParameter("artigoId", artigoId) :
                new ObjectParameter("artigoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("atualizarArtigo", update1Parameter, artigoIdParameter);
        }
    
        public virtual int atualizarLocal(Nullable<decimal> preco, string locOrigem, string locDestino)
        {
            var precoParameter = preco.HasValue ?
                new ObjectParameter("preco", preco) :
                new ObjectParameter("preco", typeof(decimal));
    
            var locOrigemParameter = locOrigem != null ?
                new ObjectParameter("locOrigem", locOrigem) :
                new ObjectParameter("locOrigem", typeof(string));
    
            var locDestinoParameter = locDestino != null ?
                new ObjectParameter("locDestino", locDestino) :
                new ObjectParameter("locDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("atualizarLocal", precoParameter, locOrigemParameter, locDestinoParameter);
        }
    
        public virtual int atualizarUtilizador(string email, string pp, string nome, string morada)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ppParameter = pp != null ?
                new ObjectParameter("pp", pp) :
                new ObjectParameter("pp", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("morada", morada) :
                new ObjectParameter("morada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("atualizarUtilizador", emailParameter, ppParameter, nomeParameter, moradaParameter);
        }
    
        public virtual int efetuarCompraDireta(Nullable<System.DateTime> data, string locDest, Nullable<int> cc, Nullable<int> artigoId)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            var locDestParameter = locDest != null ?
                new ObjectParameter("locDest", locDest) :
                new ObjectParameter("locDest", typeof(string));
    
            var ccParameter = cc.HasValue ?
                new ObjectParameter("cc", cc) :
                new ObjectParameter("cc", typeof(int));
    
            var artigoIdParameter = artigoId.HasValue ?
                new ObjectParameter("artigoId", artigoId) :
                new ObjectParameter("artigoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("efetuarCompraDireta", dataParameter, locDestParameter, ccParameter, artigoIdParameter);
        }
    
        public virtual int efetuarLeilao(Nullable<System.DateTime> data, string locDest, Nullable<int> cc, Nullable<int> artigoId)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            var locDestParameter = locDest != null ?
                new ObjectParameter("locDest", locDest) :
                new ObjectParameter("locDest", typeof(string));
    
            var ccParameter = cc.HasValue ?
                new ObjectParameter("cc", cc) :
                new ObjectParameter("cc", typeof(int));
    
            var artigoIdParameter = artigoId.HasValue ?
                new ObjectParameter("artigoId", artigoId) :
                new ObjectParameter("artigoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("efetuarLeilao", dataParameter, locDestParameter, ccParameter, artigoIdParameter);
        }
    
        public virtual int inserirArtigo(Nullable<System.DateTime> data)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserirArtigo", dataParameter);
        }
    
        public virtual int inserirLicitacao(Nullable<System.DateTime> data, Nullable<decimal> preco, string email, Nullable<int> artigoId)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            var precoParameter = preco.HasValue ?
                new ObjectParameter("preco", preco) :
                new ObjectParameter("preco", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var artigoIdParameter = artigoId.HasValue ?
                new ObjectParameter("artigoId", artigoId) :
                new ObjectParameter("artigoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserirLicitacao", dataParameter, precoParameter, emailParameter, artigoIdParameter);
        }
    
        public virtual int inserirLocal(Nullable<decimal> preco, string locOrigem, string locDestino)
        {
            var precoParameter = preco.HasValue ?
                new ObjectParameter("preco", preco) :
                new ObjectParameter("preco", typeof(decimal));
    
            var locOrigemParameter = locOrigem != null ?
                new ObjectParameter("locOrigem", locOrigem) :
                new ObjectParameter("locOrigem", typeof(string));
    
            var locDestinoParameter = locDestino != null ?
                new ObjectParameter("locDestino", locDestino) :
                new ObjectParameter("locDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserirLocal", precoParameter, locOrigemParameter, locDestinoParameter);
        }
    
        public virtual int inserirUtilizador(string email, string pp, string nome, string morada)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ppParameter = pp != null ?
                new ObjectParameter("pp", pp) :
                new ObjectParameter("pp", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("morada", morada) :
                new ObjectParameter("morada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserirUtilizador", emailParameter, ppParameter, nomeParameter, moradaParameter);
        }
    
        public virtual int removerLicitacao(string email, Nullable<int> artigoId)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var artigoIdParameter = artigoId.HasValue ?
                new ObjectParameter("artigoId", artigoId) :
                new ObjectParameter("artigoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removerLicitacao", emailParameter, artigoIdParameter);
        }
    
        public virtual int valuePorte(string locOrigem, string locDestino, ObjectParameter valorPorte)
        {
            var locOrigemParameter = locOrigem != null ?
                new ObjectParameter("locOrigem", locOrigem) :
                new ObjectParameter("locOrigem", typeof(string));
    
            var locDestinoParameter = locDestino != null ?
                new ObjectParameter("locDestino", locDestino) :
                new ObjectParameter("locDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("valuePorte", locOrigemParameter, locDestinoParameter, valorPorte);
        }
    
        public virtual int verificarPp(string email, string pp, ObjectParameter res)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ppParameter = pp != null ?
                new ObjectParameter("pp", pp) :
                new ObjectParameter("pp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("verificarPp", emailParameter, ppParameter, res);
        }
    }
}
