//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porte
    {
        public string moradaOrigem { get; set; }
        public string moradaDestino { get; set; }
        public decimal preco { get; set; }
    }
}
